"""
Author: Abubakar Saeed
Date: February 23, 2026
Description: RNA subcellular localization model training script using a hybrid architecture
that combines RNA language model embeddings (RiNALMo) with BioGraphX-RNA graph-physics features.
Implements 5-fold cross-validatione .

The model architecture:
- Branch 1: Processes RiNALMo embeddings (1280-dim)
- Branch 2: Processes BioGraphX-RNA physics features (149-dim)
- Gating mechanism: Learns to weight contributions from each branch per sample
- Classifier: Multi-label prediction for 9 subcellular compartments

"""
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import numpy as np
import os
from sklearn.metrics import (
    f1_score, accuracy_score, matthews_corrcoef, 
    roc_auc_score, average_precision_score, 
    precision_score, recall_score
)
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold
import warnings
import gc

warnings.filterwarnings('ignore')

# ==========================================
# 🏆 0. OPTIMIZED CONFIGURATION
# ==========================================
# Best hyperparameters found via Optuna Bayesian optimization
LEARNING_RATE = 0.000362625      # AdamW learning rate
BATCH_SIZE = 128                  # Balanced for memory and gradient stability
DROPOUT_RATE = 0.48374            # Dropout for regularization
SHARED_DIM = 512                   # Hidden dimension for both branches
FOCAL_GAMMA = 1.01773              # Focal loss gamma (focus on hard examples)

# Dataset Paths
TRAIN_CSV_PATH = "/kaggle/input/human-rna/unified_data_Encoded.csv"
TEST_CSV_PATH = "/kaggle/input/human-rna/unified_data_independent_Encoded.csv"
EMBEDDINGS_PATH = "/kaggle/input/human-rna/rinalmo_localization_fast.npz"

# Dimensions & Training Settings
EMBEDDING_DIM = 1280  # RiNALMo RNA language model embedding dimension
N_EPOCHS = 100         # Maximum epochs (early stopping will trigger sooner)
PATIENCE = 15          # Early stopping patience
N_FOLDS = 5            # 5-fold cross-validation
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
NUM_WORKERS = 4        # DataLoader workers for parallel loading

# Target Columns - 9 RNA subcellular compartments
ALL_TARGET_COLS = [
    'Nucleus', 'Exosome', 'Cytosol', 'Cytoplasm', 'Ribosome', 
    'Membrane', 'ER', 'Microvesicle', 'Mitochondrion'
]

# Official Benchmark Targets
# These 6 compartments are used for final benchmark reporting
BENCHMARK_COLS = [
    'Nucleus', 'Exosome', 'Cytosol', 'Cytoplasm', 'Ribosome', 
    'Membrane', 'ER', 'Microvesicle', 'Mitochondrion'
]

BENCHMARK_INDICES = [i for i, col in enumerate(ALL_TARGET_COLS) if col in BENCHMARK_COLS]
NUM_CLASSES = len(ALL_TARGET_COLS)

# ==========================================
# 1.  LOSS FUNCTION
# ==========================================
class FocalLoss(nn.Module):
    """
    Focal Loss for multi-label classification with class imbalance.
    
    Focal loss down-weights easy examples and focuses training on hard negatives.
    Particularly useful for RNA localization where some compartments are rare.
    
    Formula: FL(p_t) = -α(1-p_t)^γ log(p_t)
    where p_t is model's estimated probability for the true class
    
    Args:
        alpha (float): Balancing factor (default: 0.25)
        gamma (float): Focusing parameter (default: 2.0)
        reduction (str): 'mean', 'sum', or 'none'
    """
    def __init__(self, alpha=0.25, gamma=2, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.reduction = reduction

    def forward(self, inputs, targets):
        """
        Args:
            inputs: Raw logits from model (before sigmoid)
            targets: Binary labels (0 or 1)
        """
        BCE_loss = F.binary_cross_entropy_with_logits(inputs, targets, reduction='none')
        pt = torch.exp(-BCE_loss)  # p_t = sigmoid(logit) when target=1, else 1-sigmoid(logit)
        F_loss = self.alpha * (1-pt)**self.gamma * BCE_loss

        if self.reduction == 'mean': 
            return torch.mean(F_loss)
        elif self.reduction == 'sum': 
            return torch.sum(F_loss)
        else: 
            return F_loss

# ==========================================
# 2. DATA LOADING
# ==========================================
def load_embeddings(embeddings_path):
    """
    Load RiNALMo RNA language model embeddings from .npz file.
    
    The embeddings file contains pre-computed representations for each RNA sequence,
    generated by the RiNALMo model (1280-dimensional vectors).
    
    Args:
        embeddings_path: Path to .npz file
        
    Returns:
        Dictionary mapping Gene_ID to embedding vector, or None if file missing
    """
    print(f"Loading embeddings from {embeddings_path}...")
    if not os.path.exists(embeddings_path):
        print("Embedding file not found.")
        return None
    
    try:
        embeddings = np.load(embeddings_path, allow_pickle=True)
        embedding_dict = {}
        
        # Handle different possible NPZ structures
        for key in embeddings.files:
            if key == 'arr_0' or key == '0':
                data = embeddings[key]
                if hasattr(data, 'dtype') and data.dtype.names:
                    # Structured array format
                    for name in data.dtype.names:
                        embedding_dict[str(name)] = data[name]
                elif isinstance(data, dict):
                    # Dictionary format
                    embedding_dict = {str(k): v for k, v in data.items()}
            else:
                # Direct key-value format
                embedding_dict[str(key)] = embeddings[key]
                
        print(f"✅ Loaded {len(embedding_dict)} embeddings.")
        return embedding_dict
        
    except Exception as e:
        print(f"❌ Error loading embeddings: {e}")
        return None

class RNAHybridDataset(Dataset):
    """
    PyTorch Dataset for RNA sequences combining embeddings and physics features.
    
    Each sample contains:
    - Gene_ID: Identifier for looking up pre-computed embeddings
    - Physics features: 149-dimensional BioGraphX-RNA features
    - Labels: Multi-label targets for 9 compartments
    
    If embedding is missing, returns zero vector (model will rely on physics branch).
    """
    def __init__(self, df, embedding_dict, physics_array, label_matrix):
        self.gene_ids = df["Gene_ID"].values.astype(str)
        self.labels = torch.tensor(label_matrix, dtype=torch.float32)
        self.embedding_dict = embedding_dict
        self.physics = torch.tensor(physics_array, dtype=torch.float32)

    def __len__(self):
        return len(self.gene_ids)
    
    def __getitem__(self, idx):
        gene_id = self.gene_ids[idx]
        
        # Get embedding if available
        if self.embedding_dict and gene_id in self.embedding_dict:
            emb = self.embedding_dict[gene_id]
            # Handle variable-length embeddings (average pooling)
            if len(emb.shape) > 1:
                emb = np.mean(emb, axis=0)
            embedding_tensor = torch.from_numpy(emb).float()
        else:
            # Missing embedding: use zeros (model will rely on physics)
            embedding_tensor = torch.zeros(EMBEDDING_DIM, dtype=torch.float32)
            
        return embedding_tensor, self.physics[idx], self.labels[idx]

def collate_fn_rna(batch):
    """
    Custom collate function for RNAHybridDataset.
    
    Args:
        batch: List of (embedding, physics, labels) tuples
        
    Returns:
        Stacked embeddings, physics features, and labels
    """
    e, p, l = zip(*batch)
    return torch.stack(e), torch.stack(p), torch.stack(l)

# ==========================================
# 3. OPTIMIZED MODEL ARCHITECTURE
# ==========================================
class BioGraphX_RNA(nn.Module):
    """
    Hybrid architecture combining RNA language model embeddings with graph-physics features.
    
    """
    def __init__(self, embedding_dim, physics_dim, num_classes, shared_dim, dropout_rate):
        super().__init__()
        
        # Branch 1: Language Model Embeddings (RiNALMo)
        # Captures evolutionary and sequence pattern information
        self.embedding_branch = nn.Sequential(
            nn.Linear(embedding_dim, shared_dim),
            nn.BatchNorm1d(shared_dim),  # Stabilizes training
            nn.ReLU(),
            nn.Dropout(dropout_rate)     # Prevents overfitting
        )
        
        # Branch 2: Graph Physics Features (BioGraphX-RNA)
        # Encodes structural constraints and interaction networks
        # Deeper architecture to capture complex interaction patterns
        self.physics_branch = nn.Sequential(
            nn.Linear(physics_dim, shared_dim),
            nn.BatchNorm1d(shared_dim),
            nn.ReLU(),
            nn.Dropout(dropout_rate)      # Tuned dropout rate
        )
        
        # Gating Mechanism: Learns to weight branches per sample
        # Output in [0,1] range via sigmoid activation
        self.gate = nn.Sequential(
            nn.Linear(shared_dim * 2, shared_dim * 2),
            nn.Sigmoid()  # Gate values between 0 and 1
        )
        
        # Classifier: Multi-label prediction head
        self.classifier = nn.Sequential(
            nn.Linear(shared_dim * 2, shared_dim // 2),
            nn.BatchNorm1d(shared_dim // 2),
            nn.ReLU(),
            nn.Dropout(dropout_rate),
            nn.Linear(shared_dim // 2, num_classes)  # Raw logits output
        )
        
    def forward(self, embedding, physics):
        """
        Forward pass through the hybrid architecture.
        
        Args:
            embedding: RiNALMo embeddings (batch_size, 1280)
            physics: BioGraphX-RNA features (batch_size, 149)
            
        Returns:
            Logits for multi-label classification (batch_size, 9)
        """
        # Process each branch independently
        e_feat = self.embedding_branch(embedding)  # (batch, 512)
        p_feat = self.physics_branch(physics)      # (batch, 512)
        
        # Combine features
        combined = torch.cat([e_feat, p_feat], dim=1)  # (batch, 1024)
        
        # Apply gating: element-wise multiplication with learned weights
        # This allows the model to emphasize relevant features per sample
        gated = combined * self.gate(combined)  # (batch, 1024)
        
        # Final classification
        return self.classifier(gated)  # (batch, 9)
# ==========================================
# 4. EVALUATION METRICS
# ==========================================
def evaluate_metrics(model, dataloader, threshold=0.5):
    """
    Calculate metrics strictly on Benchmark Classes following " " protocol.
    """
    model.eval()
    all_targets, all_logits = [], []
    
    with torch.no_grad():
        for emb, phys, labels in dataloader:
            emb, phys = emb.to(DEVICE), phys.to(DEVICE)
            logits = model(emb, phys)
            probs = torch.sigmoid(logits)
            
            # Handle any NaN values
            if torch.isnan(probs).any():
                probs = torch.nan_to_num(probs, nan=0.0)
                
            all_logits.append(probs.cpu().numpy())
            all_targets.append(labels.numpy())
            
    y_probs = np.vstack(all_logits)
    y_true = np.vstack(all_targets)
    y_pred = (y_probs > threshold).astype(int)
    
    # Initialize metric containers
    metrics = {"auroc": [], "auprc": [], "f1": [], "mcc": [], "prec": [], "rec": []}
    
    # Calculate per-class metrics
    for i in range(NUM_CLASSES):
        # AUROC and AUPRC (handle constant columns)
        try:
            if len(np.unique(y_true[:, i])) > 1:
                auroc = roc_auc_score(y_true[:, i], y_probs[:, i])
                auprc = average_precision_score(y_true[:, i], y_probs[:, i])
            else:
                auroc, auprc = 0.5, 0.0
        except:
            auroc, auprc = 0.5, 0.0
            
        # Classification metrics
        f1 = f1_score(y_true[:, i], y_pred[:, i], zero_division=0)
        mcc = matthews_corrcoef(y_true[:, i], y_pred[:, i])
        prec = precision_score(y_true[:, i], y_pred[:, i], zero_division=0)
        rec = recall_score(y_true[:, i], y_pred[:, i], zero_division=0)
        
        metrics["auroc"].append(auroc)
        metrics["auprc"].append(auprc)
        metrics["f1"].append(f1)
        metrics["mcc"].append(mcc)
        metrics["prec"].append(prec)
        metrics["rec"].append(rec)
    
    # Macro Average on BENCHMARK CLASSES ONLY (" " protocol)
    benchmark_aurocs = [metrics["auroc"][i] for i in BENCHMARK_INDICES]
    macro_metrics = {
        "Macro_AUROC": np.nanmean(benchmark_aurocs),
        "All_Class_Macro_AUROC": np.nanmean(metrics["auroc"])
    }
    
    # Handle NaN case
    if np.isnan(macro_metrics["Macro_AUROC"]):
        macro_metrics["Macro_AUROC"] = 0.0
        
    return macro_metrics, metrics, y_probs, y_true

def optimize_thresholds(y_true, y_probs):
    """
    Find optimal per-class thresholds by maximizing Matthews Correlation Coefficient.


    """
    best_thresholds = []
    # 50-point grid search from 0 to 1 as per 
    search_space = np.linspace(0, 1, 50)
    
    for i in range(NUM_CLASSES):
        best_mcc, best_thr = -1.0, 0.5
        
        for thr in search_space:
            # Skip extreme edges to avoid zero-division in MCC
            if thr == 0 or thr == 1:
                continue
            
            # Apply threshold
            pred = (y_probs[:, i] > thr).astype(int)
            mcc = matthews_corrcoef(y_true[:, i], pred)
            
            if mcc > best_mcc:
                best_mcc = mcc
                best_thr = thr
                
        best_thresholds.append(best_thr)
        
    return np.array(best_thresholds)

# ==========================================
# 🔍 5. GATING ANALYSIS FUNCTION
# ==========================================
def analyze_gating(model, dataloader):
    """
    Analyze the gating mechanism to understand feature importance per compartment.
    
    Args:
        model: Trained BioGraphX_RNA model
        dataloader: DataLoader for analysis (typically test set)
    """
    model.eval()
    
    # Storage for all batches
    all_emb_acts = []
    all_phys_acts = []
    all_labels = []
    
    print("\n🔍 Scanning Test Set for Gate Activations...")
    
    with torch.no_grad():
        for emb, phys, labels in dataloader:
            emb, phys = emb.to(DEVICE), phys.to(DEVICE)
            
            # Forward pass components
            e_feat = model.embedding_branch(emb)
            p_feat = model.physics_branch(phys)
            combined = torch.cat([e_feat, p_feat], dim=1)
            
            # Get gate values
            gate_values = model.gate(combined)
            
            # Split gate into embedding and physics components
            split_idx = gate_values.shape[1] // 2
            g_emb = gate_values[:, :split_idx]
            g_phys = gate_values[:, split_idx:]
            
            # Store mean activation per sample
            all_emb_acts.append(g_emb.mean(dim=1).cpu().numpy())
            all_phys_acts.append(g_phys.mean(dim=1).cpu().numpy())
            all_labels.append(labels.numpy())
            
    # Concatenate all batches
    final_emb_acts = np.concatenate(all_emb_acts)   # Shape: (N_Samples,)
    final_phys_acts = np.concatenate(all_phys_acts) # Shape: (N_Samples,)
    final_labels = np.vstack(all_labels)            # Shape: (N_Samples, N_Classes)
    
    # 1. Global Analysis
    avg_emb = np.mean(final_emb_acts)
    avg_phys = np.mean(final_phys_acts)
    tot = avg_emb + avg_phys
    
    print("\n" + "="*60)
    print(f"🌍 GLOBAL GATING ANALYSIS (All {len(final_emb_acts)} samples)")
    print("="*60)
    print(f"Avg Embedding Gate: {avg_emb:.4f}  ({(avg_emb/tot)*100:.1f}%)")
    print(f"Avg Physics Gate:   {avg_phys:.4f}  ({(avg_phys/tot)*100:.1f}%)")
    print("-" * 60)
    
    # 2. Class-by-Class Analysis
    print(f"{'Compartment':<25} | {'N_Samples':<10} | {'Emb Gate':<10} | {'Phys Gate':<10} | {'Phys Reliance %':<15}")
    print("-" * 75)
    
    for i, col in enumerate(ALL_TARGET_COLS):
        # Find indices where this class is Positive (1)
        class_indices = np.where(final_labels[:, i] == 1)[0]
        n_samples = len(class_indices)
        
        if n_samples > 0:
            # Extract gate values for these specific samples
            c_emb = np.mean(final_emb_acts[class_indices])
            c_phys = np.mean(final_phys_acts[class_indices])
            
            c_tot = c_emb + c_phys
            phys_pct = (c_phys / c_tot) * 100
            
            print(f"{col:<25} | {n_samples:<10} | {c_emb:.4f}     | {c_phys:.4f}     | {phys_pct:.1f}%")
        else:
            print(f"{col:<25} | 0          | --         | --         | --")
            
    print("="*60)
    print("Interpretation: Higher 'Phys Reliance %' means the model uses")
    print("structural graph features more heavily for that compartment.")

# ==========================================
# 🚀 6. MAIN PIPELINE
# ==========================================
def main():
    print("🚀 STARTING OPTIMIZED 5-FOLD PIPELINE")
    print(f"🔧 Params: LR={LEARNING_RATE} | Batch={BATCH_SIZE} | Drop={DROPOUT_RATE:.2f} | Gamma={FOCAL_GAMMA:.2f}")
    
    # ===== 1. Load Data =====
    train_full_df = pd.read_csv(TRAIN_CSV_PATH)
    test_df = pd.read_csv(TEST_CSV_PATH)
    all_cols = list(train_full_df.columns)

    # BioGraphX-RNA physics features are the last 149 columns
    RNA_PHYSICS_COLS = all_cols[-149:]
    
    # Ensure target columns exist
    for col in ALL_TARGET_COLS:
        if col not in train_full_df.columns:
            print(f"❌ Missing target column: {col}")
            return
        if col not in test_df.columns:
            test_df[col] = 0  # Add dummy column if missing

    # Filter to valid physics columns
    valid_physics_cols = [c for c in RNA_PHYSICS_COLS if c in train_full_df.columns]
    
    # ===== 2. Preprocessing =====
    # Standardize physics features
    scaler = StandardScaler()
    X_train_phys = scaler.fit_transform(train_full_df[valid_physics_cols]).astype(np.float32)
    X_test_phys = scaler.transform(test_df[valid_physics_cols]).astype(np.float32)
    
    # Extract labels
    Y_train_full = train_full_df[ALL_TARGET_COLS].values.astype(np.float32)
    Y_test = test_df[ALL_TARGET_COLS].values.astype(np.float32)
    
    # Load embeddings
    embedding_dict = load_embeddings(EMBEDDINGS_PATH)
    
    # ===== 3. K-Fold Setup =====
    kfold = KFold(n_splits=N_FOLDS, shuffle=True, random_state=42)
    test_ensemble_probs = np.zeros((len(test_df), NUM_CLASSES))
    all_fold_thresholds = []  #store thresholds per validation fold
    fold_results = []
    
    for fold, (train_idx, val_idx) in enumerate(kfold.split(train_full_df)):
        print(f"\n{'='*20} FOLD {fold+1}/{N_FOLDS} {'='*20}")
        
        # Create datasets
        train_ds = RNAHybridDataset(
            train_full_df.iloc[train_idx], 
            embedding_dict, 
            X_train_phys[train_idx], 
            Y_train_full[train_idx]
        )
        val_ds = RNAHybridDataset(
            train_full_df.iloc[val_idx], 
            embedding_dict, 
            X_train_phys[val_idx], 
            Y_train_full[val_idx]
        )
        
        # Create dataloaders
        train_dl = DataLoader(
            train_ds, 
            batch_size=BATCH_SIZE, 
            shuffle=True, 
            collate_fn=collate_fn_rna, 
            num_workers=NUM_WORKERS
        )
        val_dl = DataLoader(
            val_ds, 
            batch_size=BATCH_SIZE, 
            shuffle=False, 
            collate_fn=collate_fn_rna, 
            num_workers=NUM_WORKERS
        )
        
        # Initialize model
        model = BioGraphX_RNA(
            EMBEDDING_DIM, 
            len(valid_physics_cols), 
            NUM_CLASSES, 
            SHARED_DIM, 
            DROPOUT_RATE
        ).to(DEVICE)
        
        # Loss, optimizer, scheduler
        criterion = FocalLoss(alpha=0.25, gamma=FOCAL_GAMMA)
        optimizer = torch.optim.AdamW(
            model.parameters(), 
            lr=LEARNING_RATE, 
            weight_decay=1e-3
        )
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
            optimizer, 
            mode='max', 
            factor=0.5, 
            patience=5
        )
        
        # Training loop variables
        best_metric = -1.0
        best_model_state = None
        patience_counter = 0
        
        # ===== 4. Training Loop =====
        for epoch in range(N_EPOCHS):
            model.train()
            train_loss = 0
            
            for emb, phys, labels in train_dl:
                emb, phys, labels = emb.to(DEVICE), phys.to(DEVICE), labels.to(DEVICE)
                
                optimizer.zero_grad()
                loss = criterion(model(emb, phys), labels)
                loss.backward()
                
                # Gradient clipping for stability
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
                
                train_loss += loss.item()
            
            # Validation
            macro, _, _, _ = evaluate_metrics(model, val_dl)
            curr_metric = macro["Macro_AUROC"]
            scheduler.step(curr_metric)
            
            # Save best model
            if curr_metric > best_metric:
                best_metric = curr_metric
                best_model_state = model.state_dict().copy()
                patience_counter = 0
            else:
                patience_counter += 1
            
            # Progress update
            print(f"Epoch {epoch+1}: Loss {train_loss/len(train_dl):.4f} | Benchmark AUROC {curr_metric:.4f} | Best {best_metric:.4f}", end='\r')
            
            # Early stopping
            if patience_counter >= PATIENCE:
                break

        # ===== 5. Post-Fold Optimization =====
        model.load_state_dict(best_model_state)
        torch.save(model.state_dict(), f"best_model_fold_{fold+1}.pth")
        fold_results.append(best_metric)

        # --- Validation-based Threshold Optimization ---
        print(f"\n🔍 Optimizing Thresholds on Validation Fold {fold+1}...")
        _, _, val_probs, val_true = evaluate_metrics(model, val_dl)
        fold_opt_thrs = optimize_thresholds(val_true, val_probs)
        print(f"Optimal thresholds: {fold_opt_thrs}")
        all_fold_thresholds.append(fold_opt_thrs)
        
        # Add to Test Ensemble
        test_ds_fold = RNAHybridDataset(test_df, embedding_dict, X_test_phys, Y_test)
        test_dl_fold = DataLoader(
            test_ds_fold, 
            batch_size=BATCH_SIZE, 
            shuffle=False, 
            collate_fn=collate_fn_rna
        )
        _, _, test_logits, _ = evaluate_metrics(model, test_dl_fold)
        test_ensemble_probs += test_logits / N_FOLDS
        
        # Cleanup
        del model
        torch.cuda.empty_cache()
        gc.collect()

    # ===== 6. Final Global Calculations =====
    print(f"\nAverage Benchmark AUROC Across Folds: {np.nanmean(fold_results):.4f}")
    
    # Calculate Final Ensemble Thresholds (Mean of best thresholds per fold)
    final_vld_thresholds = np.mean(all_fold_thresholds, axis=0)
    
    print("\n" + "="*45)
    print(" FINAL ENSEMBLED THRESHOLDS")
    print("-" * 45)
    for i, col in enumerate(ALL_TARGET_COLS):
        print(f"{col:<20}: {final_vld_thresholds[i]:.4f}")
    print("="*45)

    # Apply averaged validation thresholds to test ensemble probabilities
    test_preds_opt = np.zeros_like(test_ensemble_probs)
    for i in range(NUM_CLASSES):
        test_preds_opt[:, i] = (test_ensemble_probs[:, i] > final_vld_thresholds[i]).astype(int)

    # ===== 7. Final Metric Reports (Using optimized predictions) =====
    print(f"\n{'='*40} TABLE 1 (BENCHMARK) {'='*40}")
    print(f"{'Compartment':<20} | {'F1':<8} | {'MCC':<8} | {'AUROC':<8} | {'AUPRC':<8}")
    print("-" * 75)
    
    final_metrics = {"f1": [], "mcc": [], "auroc": [], "auprc": []}
    for i in BENCHMARK_INDICES:
        col = ALL_TARGET_COLS[i]
        
        # Calculate metrics
        try:
            auroc = roc_auc_score(Y_test[:, i], test_ensemble_probs[:, i])
        except:
            auroc = 0.5
            
        try:
            auprc = average_precision_score(Y_test[:, i], test_ensemble_probs[:, i])
        except:
            auprc = 0.0
        
        mcc = matthews_corrcoef(Y_test[:, i], test_preds_opt[:, i])
        f1 = f1_score(Y_test[:, i], test_preds_opt[:, i], zero_division=0)
        
        # Store metrics
        final_metrics["f1"].append(f1)
        final_metrics["mcc"].append(mcc)
        final_metrics["auroc"].append(auroc)
        final_metrics["auprc"].append(auprc)
        
        # Print row
        print(f"{col:<20} | {f1:.4f}   | {mcc:.4f}   | {auroc:.4f}   | {auprc:.4f}")
        
    print("-" * 75)
    print(f"MACRO AVERAGE (BENCH) | {np.mean(final_metrics['f1']):.4f}   | {np.mean(final_metrics['mcc']):.4f}   | {np.mean(final_metrics['auroc']):.4f}   | {np.mean(final_metrics['auprc']):.4f}")

    # ===== 8. Save Submission =====
    submission = pd.DataFrame(test_preds_opt, columns=ALL_TARGET_COLS)
    submission.insert(0, "Gene_ID", test_df["Gene_ID"])
    submission.to_csv("final_optimized_predictions.csv", index=False)
    print("\n✅ Results saved to final_optimized_predictions.csv")

    # ===== 9. Gating Analysis (using Fold 5 weights as representative) =====
    print("\n" + "="*50)
    print("🧠 RUNNING GATING ANALYSIS")
    print("="*50)
    
    model = BioGraphX_RNA(
        EMBEDDING_DIM, 
        len(valid_physics_cols), 
        NUM_CLASSES, 
        SHARED_DIM, 
        DROPOUT_RATE
    ).to(DEVICE)
    model.load_state_dict(torch.load(f"best_model_fold_{N_FOLDS}.pth"))
    
    analysis_ds = RNAHybridDataset(test_df, embedding_dict, X_test_phys, Y_test)
    analysis_dl = DataLoader(
        analysis_ds, 
        batch_size=BATCH_SIZE, 
        shuffle=False, 
        collate_fn=collate_fn_rna
    )
    analyze_gating(model, analysis_dl)

if __name__ == "__main__":
    main()
