"""
Author: Abubakar Saeed
Date: February 23, 2026
Description: RNA feature name definitions for subcellular localization prediction.
These feature names correspond to the 149-dimensional feature vector generated by
the RNAsubLocalizationPipeline. Each feature group captures different aspects of
RNA biology including graph topology, hybrid interactions, motif profiles,
physicochemical properties, and structural frustration.

"""

# =============================================================================
# 1. BASIC RNA GRAPH FEATURES (65 dimensions)
# =============================================================================
"""
Basic graph features capture the topology and interaction patterns of the RNA
constraint graph. These features quantify network properties derived from
RNA-specific interactions (canonical pairing, wobble pairs, stacking, backbone).
"""
RNA_BASIC_GRAPH_NAMES = [
    # Basic topology (3)
    # Fundamental graph properties describing overall network structure
    "Node_Count",  # Number of nucleotides (nodes) in the graph
    "Edge_Count",  # Number of interactions (edges) detected
    "Graph_Density",  # Edge density: actual_edges / possible_edges

    # Degree statistics (6)
    # Distribution of node connectivity (number of interactions per nucleotide)
    "Mean_Degree",  # Average number of interactions per nucleotide
    "Degree_Std",  # Standard deviation of degree distribution
    "Max_Degree",  # Maximum degree (most connected nucleotide)
    "Degree_Q1",  # First quartile of degree distribution
    "Degree_Median",  # Median degree
    "Degree_Q3",  # Third quartile of degree distribution

    # Weighted degree (3)
    # Degree measures weighted by interaction strength
    "Mean_Weighted_Degree",  # Average interaction strength per nucleotide
    "Weighted_Degree_Std",  # Standard deviation of weighted degree
    "Max_Weighted_Degree",  # Maximum weighted degree (strongest connected)

    # RNA interaction type ratios (5)
    # Relative frequency of each interaction type in the graph
    "Canonical_WC_Ratio",  # Proportion of Watson-Crick pairs (A-U, G-C)
    "Wobble_Pair_Ratio",  # Proportion of G-U wobble pairs
    "Non_Canonical_Ratio",  # Proportion of other non-canonical pairs
    "Base_Stacking_Ratio",  # Proportion of stacking interactions
    "Backbone_Ratio",  # Proportion of backbone connections

    # Energy-based features (5)
    # Thermodynamic properties derived from interaction energies
    "Mean_Interaction_Energy",  # Average energy per interaction (kcal/mol)
    "Energy_Std",  # Standard deviation of interaction energies
    "Min_Energy",  # Minimum (most negative) energy - strongest interaction
    "Total_Stabilization",  # Sum of all interaction energies
    "Strong_Interactions_Ratio",  # Proportion of interactions with energy < -1.0 kcal/mol

    # Centrality features (10)
    # Measures of node importance in the network (with cutoff=10 for efficiency)
    "Mean_Betweenness",  # Average betweenness centrality (nodes on shortest paths)
    "Betweenness_Std",  # Standard deviation of betweenness
    "Max_Betweenness",  # Maximum betweenness (structural bottlenecks)
    "Mean_Closeness",  # Average closeness centrality (nodes near others)
    "Closeness_Std",  # Standard deviation of closeness
    "Max_Closeness",  # Maximum closeness (centrally located nodes)
    "Min_Closeness",  # Minimum closeness (peripheral nodes)
    "Mean_Eigenvector",  # Average eigenvector centrality (influence)
    "Eigenvector_Std",  # Standard deviation of eigenvector centrality

    # Community features (6)
    # Detection of structural domains/modules in RNA
    "Community_Count",  # Number of structural domains detected
    "Modularity",  # Quality of community division (0-1)
    "Mean_Community_Size",  # Average size of structural domains
    "Community_Size_Std",  # Standard deviation of domain sizes
    "Max_Community_Size",  # Size of largest structural domain
    "IntraCommunity_Edge_Ratio",  # Proportion of edges within communities (domain cohesion)

    # RNA localization patterns (12)
    # Region-specific graph properties in functionally important areas
    "Five_Prime_Connectivity",  # Edge density in 5' region (first 30 nt)
    "Five_Prime_GC",  # GC content in 5' region (structural potential)
    "Five_Prime_Strong_Edges",  # Strong interaction ratio in 5' region
    "Three_Prime_Connectivity",  # Edge density in 3' region (last 30 nt)
    "Three_Prime_AU",  # AU content in 3' region (flexibility signal)
    "Three_Prime_Terminal_Degree",  # Connectivity of 3' terminal nucleotide
    "GC_Cluster_Connectivity",  # Edge density within GC-rich regions
    "GC_Cluster_Count",  # Number of GC-rich clusters
    "Max_GC_Cluster_Size",  # Size of largest GC-rich cluster
    "AU_Cluster_Connectivity",  # Edge density within AU-rich regions
    "AU_Cluster_Count",  # Number of AU-rich clusters
    "Max_AU_Cluster_Size",  # Size of largest AU-rich cluster

    # Path features (6)
    # Communication paths and efficiency measures
    "Avg_Shortest_Path",  # Average shortest path length between nucleotides
    "Graph_Diameter",  # Maximum shortest path (graph diameter)
    "Global_Efficiency",  # 1/avg_path - information transfer efficiency
    "Local_Efficiency",  # Average efficiency of local neighborhoods
    "Path_Length_Std",  # Standard deviation of path lengths
    "Max_Path_Length",  # Maximum path length observed

    # Additional RNA metrics (10)
    # Supplementary graph properties specific to RNA
    "Clustering_Coefficient",  # Local connectivity density (triangles)
    "Assortativity",  # Degree correlation (preferential attachment)
    "Strong_Interaction_Ratio",  # Overall ratio of strong interactions
    "Mean_Energy",  # Mean interaction energy (repeated for clarity)
    "Min_Energy_Overall",  # Minimum energy overall (most stable)
    "Stabilization_Per_Nucleotide",  # Total energy per nucleotide
    "Hybrid_Edge_Ratio",  # Overall ratio of hybrid edges
    "Mean_Edge_Weight",  # Average edge weight (interaction strength)
    "Edge_Weight_Std",  # Standard deviation of edge weights
    "Max_Edge_Weight"  # Maximum edge weight (strongest interaction)
]

# =============================================================================
# 2. RNA HYBRID FEATURE NAMES (15 dimensions)
# =============================================================================
"""
Hybrid features capture combined interactions where multiple interaction types
occur between the same nucleotides, indicating enhanced structural stability
and potential functional significance.
"""
RNA_HYBRID_FEATURE_NAMES = [
    # Basic hybrid scores (3)
    # Normalized scores for each hybrid interaction type
    "WC_Stacking_Hybrid",  # Watson-Crick + Stacking hybrid score
    "Wobble_Stacking_Hybrid",  # Wobble + Stacking hybrid score
    "Stacking_Backbone_Hybrid",  # Stacking + Backbone hybrid score

    # Regional hybrid density (4)
    # Concentration of hybrid interactions in specific regions
    "Five_Prime_Hybrid_Density",  # Hybrid edge density in 5' region
    "Three_Prime_Hybrid_Density",  # Hybrid edge density in 3' region
    "GC_Region_Hybrid_Density",  # Hybrid edge density in GC-rich regions
    "AU_Region_Hybrid_Density",  # Hybrid edge density in AU-rich regions

    # Hybrid network properties (3)
    # Graph properties of the hybrid interaction subnetwork
    "Hybrid_Edge_Ratio_Detailed",  # Detailed ratio of hybrid edges
    "Hybrid_Subgraph_Density",  # Density of hybrid-only interactions
    "Hybrid_Cluster_Count",  # Number of hybrid interaction clusters

    # Hybrid energy features (3)
    # Energetic properties of hybrid interactions
    "Mean_Hybrid_Energy",  # Average energy of hybrid interactions
    "Min_Hybrid_Energy",  # Minimum (most stable) hybrid energy
    "Strong_Hybrid_Ratio",  # Ratio of strong hybrid interactions

    # Advanced hybrid metrics (2)
    # Higher-order hybrid interaction properties
    "Hybrid_Diversity",  # Shannon entropy of hybrid type distribution
    "Hybrid_Connectivity"  # Average degree in hybrid subnetwork
]

# =============================================================================
# 3. RNA PROFILE FEATURE NAMES (27 dimensions)
# =============================================================================
"""
Profile features combine three types of evidence for each of nine subcellular
compartments: motif-based scores, hybrid interaction scores, and GC content
compatibility. These features are derived from RNAMotifProfiler.
"""
RNA_PROFILE_FEATURE_NAMES = []
for loc in ["Nucleus", "Exosome", "Cytosol", "Cytoplasm", "Ribosome",
            "Membrane", "Endoplasmic.reticulum", "Microvesicles", "Mitochondrion"]:
    RNA_PROFILE_FEATURE_NAMES.extend([
        f"Profile_{loc}_Motif",  # Motif-based localization score
        f"Profile_{loc}_Hybrid",  # Hybrid interaction compatibility score
        f"Profile_{loc}_GC_Compat"  # GC content compatibility with compartment
    ])

# =============================================================================
# 4. RNA PHYSICS FEATURE NAMES (25 dimensions)
# =============================================================================
"""
Physics features capture global physicochemical properties of RNA sequences
including composition, entropy, energy estimates, and sequence autocorrelation.
Derived from RNAPhysicsStrategy.
"""
RNA_PHYSICS_NAMES = [
    # Basic composition (2)
    "GC_Content",  # Fraction of G and C nucleotides
    "AU_Content",  # Fraction of A and U nucleotides

    # Nucleotide frequencies (4)
    "A_Frequency",  # Frequency of Adenine
    "U_Frequency",  # Frequency of Uracil
    "G_Frequency",  # Frequency of Guanine
    "C_Frequency",  # Frequency of Cytosine

    # Skew measures (2)
    "GC_Skew",  # (G-C)/(G+C) - asymmetry in GC distribution
    "AU_Skew",  # (A-U)/(A+U) - asymmetry in AU distribution

    # Complexity and energy (2)
    "Shannon_Entropy",  # Sequence complexity (bits)
    "MFE_Per_Nucleotide",  # Approximate minimum free energy per nucleotide

    # Dinucleotide frequencies (10)
    "AA_Frequency",  # Frequency of AA dinucleotide
    "UU_Frequency",  # Frequency of UU dinucleotide
    "GG_Frequency",  # Frequency of GG dinucleotide
    "CC_Frequency",  # Frequency of CC dinucleotide
    "AU_Frequency",  # Frequency of AU dinucleotide
    "UA_Frequency",  # Frequency of UA dinucleotide
    "GC_Frequency",  # Frequency of GC dinucleotide
    "CG_Frequency",  # Frequency of CG dinucleotide
    "GU_Frequency",  # Frequency of GU dinucleotide
    "UG_Frequency",  # Frequency of UG dinucleotide

    # Pairing potential statistics (4)
    "Mean_Pairing_Potential",  # Average base pairing potential (sliding window)
    "Std_Pairing_Potential",  # Standard deviation of pairing potential
    "Max_Pairing_Potential",  # Maximum local pairing potential
    "Min_Pairing_Potential",  # Minimum local pairing potential

    # Autocorrelation (1)
    "GC_Autocorrelation_Lag1"  # GC property autocorrelation at lag 1
]

# =============================================================================
# 5. RNA FRUSTRATION FEATURE NAMES (17 dimensions)
# =============================================================================
"""
Frustration features quantify conflicting structural constraints, competing
interaction patterns, and sequence-structure mismatches. Derived from
RNAFrustrationAnalyzer.
"""
RNA_FRUSTRATION_FEATURE_NAMES = [
    # Regional frustration (3)
    "Frustration_5Prime_Mean",  # Average frustration in 5' region
    "Frustration_3Prime_Mean",  # Average frustration in 3' region
    "Frustration_Middle_Mean",  # Average frustration in middle region

    # Nucleotide-type specific frustration (4)
    "Frustration_GC_Mean",  # Average frustration at GC nucleotides
    "Frustration_GC_Variance",  # Variance of frustration at GC nucleotides
    "Frustration_AU_Mean",  # Average frustration at AU nucleotides
    "Frustration_AU_Variance",  # Variance of frustration at AU nucleotides

    # Structural contrasts (2)
    "Frustration_5vs3_Prime",  # Frustration difference: 5' minus 3' region
    "Frustration_StructuredVsFlexible",  # Frustration difference: GC minus AU

    # Secondary structure frustration (1)
    "Frustration_Paired_Mean",  # Average frustration at paired nucleotides

    # Hotspot analysis (2)
    "Frustration_HotspotCount",  # Number of high-frustration positions
    "Frustration_HotspotDensity",  # Density of frustration hotspots

    # Motif-associated frustration (3)
    "Frustration_Motif_Mean",  # Average frustration in motif regions
    "Frustration_Motif_Max",  # Maximum frustration in motif regions
    "Frustration_NonMotif_Mean",  # Average frustration in non-motif regions

    # Long-range frustration (1)
    "Frustration_LongRange_Mean",  # Average frustration at long-range interaction sites

    # Global frustration (1)
    "Frustration_Entropy"  # Entropy of frustration distribution
]

# =============================================================================
# 6. COMPLETE FEATURE SET (149 dimensions)
# =============================================================================
"""
Complete feature vector combining all five feature groups in the following order:
1. Basic graph features (65)
2. Hybrid features (15)
3. Profile features (27)
4. Physics features (25)
5. Frustration features (17)
Total: 65 + 15 + 27 + 25 + 17 = 149 features

This comprehensive feature set is designed for machine learning applications
in RNA subcellular localization prediction, capturing:
- Structural properties (graph, frustration)
- Energetic properties (physics, hybrid)
- Functional signals (profile, motifs)
- Regional biases (5'/3', GC/AU)
"""
RNA_COMPLETE_FEATURE_NAMES = (RNA_BASIC_GRAPH_NAMES + RNA_HYBRID_FEATURE_NAMES +
                              RNA_PROFILE_FEATURE_NAMES + RNA_PHYSICS_NAMES + RNA_FRUSTRATION_FEATURE_NAMES)